services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
        - "16686:16686"   # UI
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
            reservations:
                cpus: '0.5'
                memory: 256M

  sql2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Bcd.1234
    ports:
      - "5000:1433"
    volumes:
      - sql2-data:/var/opt/mssql
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 1024M
            reservations:
                cpus: '0.5'
                memory: 512M

  commandservice:
    image: commandservice
    build:
      context: .
      dockerfile: Services/CommandService/Dockerfile
    depends_on:
      - sql2
      - platformservice
    deploy:
        resources:
            limits:
                cpus: '0.5'
                memory: 512M
            reservations:
                cpus: '0.25'
                memory: 256M

  platformservice:
    image: platformservice
    build:
      context: .
      dockerfile: Services/PlatformService/Dockerfile
    depends_on:
      - sql2
      - otel-collector
    deploy:
        resources:
            limits:
                cpus: '0.5'
                memory: 512M
            reservations:
                cpus: '0.25'
                memory: 256M

  platformcommandui:
    image: platformcommandui
    build:
      dockerfile: Dockerfile
      context: ./UI/platformcommandui
    ports:
      - "3000:80"
    depends_on:
      - commandservice
      - platformservice
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "9464:9464"   # expose Prometheus scrape endpoint
    depends_on:
        - jaeger
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
            reservations:
                cpus: '0.5'
                memory: 256M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
        - "9090:9090"
    depends_on:
        - otel-collector
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
            reservations:
                cpus: '0.5'
                memory: 256M

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
        - "3100:3100"
    command: >
        -config.file=/etc/loki/local-config.yaml
        -config.expand-env=true
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
            reservations:
                cpus: '0.5'
                memory: 256M

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
            reservations:
                cpus: '0.5'
                memory: 256M

volumes:
  sql2-data:
  grafana-storage:

