services:
  sql2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Bcd.1234
    ports:
      - "5000:1433"
    volumes:
      - sql2-data:/var/opt/mssql
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 1024M
            reservations:
                cpus: '0.5'
                memory: 512M

  commandservice:
    image: commandservice
    build:
      context: .
      dockerfile: Services/CommandService/Dockerfile
    depends_on:
      - sql2
      - platformservice
    deploy:
        resources:
            limits:
                cpus: '0.5'
                memory: 512M
            reservations:
                cpus: '0.25'
                memory: 256M

  platformservice:
    image: platformservice
    build:
      context: .
      dockerfile: Services/PlatformService/Dockerfile
    depends_on:
      - sql2
    deploy:
        resources:
            limits:
                cpus: '0.5'
                memory: 512M
            reservations:
                cpus: '0.25'
                memory: 256M

  platformcommandui:
    image: platformcommandui
    build:
      dockerfile: Dockerfile
      context: ./UI/platformcommandui
    ports:
      - "3000:80"
    depends_on:
      - commandservice
      - platformservice
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  sql2-data:

